# Generated by Django 3.0.7 on 2021-05-01 06:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_auto_20210501_1130'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='product_info1',
            new_name='product_info',
        ),
    ]
