# Generated by Django 3.0.7 on 2021-05-01 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_auto_20210501_1155'),
    ]

    operations = [
        migrations.CreateModel(
            name='product_info1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=20)),
                ('product_price', models.IntegerField()),
                ('product_des', models.CharField(max_length=30)),
                ('product_contact', models.IntegerField()),
                ('product_image', models.ImageField(upload_to='pics')),
            ],
        ),
        migrations.DeleteModel(
            name='product_info',
        ),
    ]
