# Generated by Django 3.0.7 on 2021-05-01 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_auto_20210501_1257'),
    ]

    operations = [
        migrations.CreateModel(
            name='userregistration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=30)),
                ('retype_password', models.CharField(max_length=30)),
            ],
        ),
        migrations.AlterField(
            model_name='product_info1',
            name='product_contact',
            field=models.IntegerField(),
        ),
    ]
